{
 "title": "RPi Monitoring",
 "description": "Raspberry Pi (4) general system monitoring dashboard.",
 "tags": [
  "influxdb",
  "telegraf",
  "raspberrypi",
  "pi4",
  "system"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   { "name": "inter", "label": "Sampling", "query": "10s,30s,1m,2m,5m,10m,30m,1h" },
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint",
    "query": "SHOW TAG VALUES FROM \"disk\" WITH KEY = \"path\" WHERE host =~ /$server/"
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": "SHOW TAG VALUES FROM \"cpu\" WITH KEY = \"cpu\" WHERE host =~ /$server/"
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"name\" WHERE host =~ /$server/"
   },
   {
    "name": "netif",
    "label": "Network interface",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE host =~ /$server/"
   },
   {
    "name": "processes",
    "label": "Processes",
    "query": "SHOW TAG VALUES FROM \"procstat\" WITH KEY = \"process_name\""
   },
   {
    "name": "user",
    "label": "User",
    "query": "SHOW TAG VALUES FROM \"procstat\" WITH KEY = \"user\""
   }
  ]
 },
 "panels": [
  { "title": "Quick overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "RootFS usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "system",
     "query": "SELECT \"uptime\" FROM \"system\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Blocked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "blocked" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total_threads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Sent (1d)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" }
     ],
     "limit": "1",
     "measurement": "net",
     "query": "SELECT  sum(\"bsent\") FROM (SELECT non_negative_difference(last(\"bytes_sent\")) AS \"bsent\" FROM \"net\" WHERE (\"host\" =~ /^$server$/ AND \"interface\" =~ /^$netif$/) AND $timeFilter GROUP BY time(10s) fill(none))",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$netif$/" }
     ]
    }
   ]
  },
  {
   "title": "Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "net",
     "query": "SELECT  sum(\"bsent\") FROM (SELECT non_negative_difference(last(\"bytes_sent\")) AS \"bsent\" FROM \"net\" WHERE (\"host\" =~ /^$server$/ AND \"interface\" =~ /^$netif$/) AND $timeFilter GROUP BY time(10s) fill(none))",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$netif$/" }
     ]
    }
   ]
  },
  {
   "title": "Throttled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "rpi_throttling",
     "select": [
      [
       { "params": [ "since_boot_throttled" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "rpi_cpu_temp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "rpi_gpu_temp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "HDD Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "hddtemp",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Zombies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "processes",
     "select": [
      [
       { "params": [ "zombies" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "LA medium",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "IOWait",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "cpu",
     "query": "SELECT non_negative_derivative(mean(\"usage_iowait\"), 1s) FROM \"cpu\" WHERE \"host\" =~ /^$server$/ AND \"cpu\" = 'cpu-total' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Received (1d)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" }
     ],
     "limit": "1",
     "measurement": "net",
     "query": "SELECT  sum(\"bsent\") FROM (SELECT non_negative_difference(last(\"bytes_sent\")) AS \"bsent\" FROM \"net\" WHERE (\"host\" =~ /^$server$/ AND \"interface\" =~ /^$netif$/) AND $timeFilter GROUP BY time(10s) fill(none))",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$netif$/" }
     ]
    }
   ]
  },
  {
   "title": "Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "net",
     "query": "SELECT non_negative_difference(last(\"bytes_recv\")) FROM \"net\" WHERE (\"host\" =~ /^$server$/ AND \"interface\" =~ /^$netif$/) AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$netif$/" }
     ]
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU usage per core",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$server: $tag_cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" }
     ],
     "measurement": "cpu",
     "query": "SELECT max(\"usage_idle\") 100 - FROM \"cpu\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval), \"cpu\"",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Load averages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$server: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"load1\"), mean(\"load5\"), mean(\"load15\") FROM \"system\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "short" ], "type": "alias" }
      ],
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "medium" ], "type": "alias" }
      ],
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "long" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU clock",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu_clock",
     "select": [
      [
       { "params": [ "arm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Clock" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Volts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rpi_volts",
     "select": [
      [
       { "params": [ "core" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Voltage" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Context switches",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$server: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "kernel",
     "select": [
      [
       { "params": [ "context_switches" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "context switches" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Forks",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$server: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "kernel",
     "select": [
      [
       { "params": [ "processes_forked" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "forks" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_irq",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "irq" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interrupts",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$server: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "running" ], "type": "alias" }
      ],
      [
       { "params": [ "blocked" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "blocked" ], "type": "alias" }
      ],
      [
       { "params": [ "stopped" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "stopped" ], "type": "alias" }
      ],
      [
       { "params": [ "zombies" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "zombies" ], "type": "alias" }
      ],
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "total" ], "type": "alias" }
      ],
      [
       { "params": [ "sleeping" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "sleeping" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent", "label": "CPU Usage %" }
   ],
   "targets": [
    {
     "alias": "$server: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "iowait" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_softirq" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "softirq" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Processses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "$server  - Processes CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
     "repeat": "server_m",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_process_name - $tag_user",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "process_name" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "pattern" ], "type": "tag" },
        { "params": [ "user" ], "type": "tag" }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "params": [ "cpu_usage" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "slimit": 10,
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "process_name", "operator": "=~", "value": "/^$processes$/" },
        { "condition": "AND", "key": "user", "operator": "=~", "value": "/^$user$/" }
       ]
      }
     ]
    },
    {
     "title": "$server  - Processes Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_process_name - $tag_user",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "process_name" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "pattern" ], "type": "tag" },
        { "params": [ "user" ], "type": "tag" }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "params": [ "memory_rss" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "slimit": "10",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "process_name", "operator": "=~", "value": "/^$processes$/" },
        { "condition": "AND", "key": "user", "operator": "=~", "value": "/^$user$/" }
       ]
      }
     ]
    },
    {
     "title": "$server  - Processes Number of threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_process_name - $tag_user",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "process_name" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "pattern" ], "type": "tag" },
        { "params": [ "user" ], "type": "tag" }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "params": [ "num_threads" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "slimit": "10",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "process_name", "operator": "=~", "value": "/^$processes$/" },
        { "condition": "AND", "key": "user", "operator": "=~", "value": "/^$user$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Throttling",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throttled (Now)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "limit": "1",
       "measurement": "rpi_throttling",
       "select": [
        [
         { "params": [ "now_throttled" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Undervolted (Now)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "limit": "1",
       "measurement": "rpi_throttling",
       "select": [
        [
         { "params": [ "now_undervolted" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "ARM Freq capped (Now)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "limit": "1",
       "measurement": "rpi_throttling",
       "select": [
        [
         { "params": [ "now_arm_frequency_capped" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Soft Temp Reached (Now)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "limit": "1",
       "measurement": "rpi_throttling",
       "select": [
        [
         { "params": [ "now_soft_temp_limit_reached" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Throttled (Boot)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "limit": "1",
       "measurement": "rpi_throttling",
       "select": [
        [
         { "params": [ "since_boot_throttled" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Undervolted (Boot)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "limit": "1",
       "measurement": "rpi_throttling",
       "select": [
        [
         { "params": [ "since_boot_undervolted" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "ARM Freq capped (Boot)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "limit": "1",
       "measurement": "rpi_throttling",
       "select": [
        [
         {
          "params": [
           "since_boot_arm_frequency_capped"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Soft Temp Reached (Boot)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "limit": "1",
       "measurement": "rpi_throttling",
       "select": [
        [
         {
          "params": [
           "since_boot_soft_temp_limit_reached"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$server: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"used_percent\") FROM \"mem\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($interval) fill(null) ",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "total" ], "type": "alias" }
      ],
      [
       { "params": [ "cached" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "cache" ], "type": "alias" }
      ],
      [
       { "params": [ "buffered" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "buffer" ], "type": "alias" }
      ],
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "used_percent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Network interface stats for $netif",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "repeat": "netif",
   "collapsed": true,
   "panels": [
    {
     "title": "Network Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$server: $netif: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "in" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$netif$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "$server: $netif: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "packets_recv" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "in" ], "type": "alias" }
        ],
        [
         { "params": [ "packets_sent" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$netif$/" }
       ]
      }
     ]
    },
    {
     "title": "TCP connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$server: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "netstat",
       "select": [
        [
         { "params": [ "tcp_close" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "closed" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_close_wait" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "close wait" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_closing" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "closing" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_established" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "established" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_fin_wait1" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "fin wait1" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_fin_wait2" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "fin wait2" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_last_ack" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "last ack" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_syn_recv" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "sync recv" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_syn_sent" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "sync rsent" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_time_wait" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "time wait" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "UDP datagrams",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "$server: $netif: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "udp_outdatagrams" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "out" ], "type": "alias" }
        ],
        [
         { "params": [ "udp_indatagrams" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "in" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Swap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Swap I/O bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$server: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "swap",
       "select": [
        [
         { "params": [ "in" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "in" ], "type": "alias" }
        ],
        [
         { "params": [ "out" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Swap usage (bytes)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 95 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$server: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "swap",
       "select": [
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "used" ], "type": "alias" }
        ],
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "total" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk IOPS for /dev/$disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "repeat": "disk",
   "collapsed": true,
   "panels": [
    {
     "title": "Disk I/O requests for /dev/$disk",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$server: $disk: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ],
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$disk$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk I/O bytes for /dev/$disk",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$server: $disk: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ],
        [
         { "params": [ "write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$disk$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk I/O time for /dev/$disk",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$server: $disk: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "read_time" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ],
        [
         { "params": [ "write_time" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$disk$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk space usage for $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "repeat": "mountpoint",
   "collapsed": true,
   "panels": [
    {
     "title": "Disk usage for $mountpoint",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$server: $mountpoint - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "total" ], "type": "alias" }
        ],
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "used" ], "type": "alias" }
        ],
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "perc" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "path", "operator": "=~", "value": "/^$mountpoint$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk inodes for $mountpoint",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 104 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$server: $mountpoint - $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "disk",
       "query": "SELECT mean(inodes_used) as \"used\" FROM \"disk\" WHERE \"host\" =~ /$server$/  AND \"path\" =~ /^$mountpoint$/ AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
       "select": [
        [
         { "params": [ "inodes_free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "free" ], "type": "alias" }
        ],
        [
         { "params": [ "inodes_used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "used" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" },
        { "condition": "AND", "key": "path", "operator": "=~", "value": "/^$mountpoint$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Uptime Graph",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Throttling",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "rpi_throttling",
     "select": [
      [
       { "params": [ "since_boot_throttled" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "rpi_cpu_temp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Note on alerts",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 87 },
   "options": {
    "content": "At the time of writing alerts do not support templated variables and only work on graphs. Therefore these dedicated panels were created to enable alerts.\n         "
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}